GET http://localhost:3001

###

GET http://localhost:3001/api/ingredients

###
GET http://localhost:3001/api/recipes

###

POST http://localhost:3001/api/ingredients
content-type: application/json

{
  "name": "Orange Peel",
  "description": "citrus fruit, warm, spicy",
  "isDry": true,
  "defaultAmount": 6
}